accessing
wrappedException: anError
	
	wrappedException := anError